'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("StreetFighter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bg_bison() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_bison", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_blanka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_blanka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_sagat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_sagat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chunli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chunli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chunli_kick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chunli_kick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chunli_kicks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chunli_kicks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chunli_punch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chunli_punch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chunli_walkb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chunli_walkb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chunli_walkf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chunli_walkf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guile_kick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guile_kick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guile_punch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guile_punch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guile_sonicboom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guile_sonicboom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guile_walkb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guile_walkb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property guile_walkf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guile_walkf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hadoken() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hadoken", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property lightningkicks() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("lightningkicks", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ryu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ryu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ryu_hadouken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ryu_hadouken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ryu_kick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ryu_kick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ryu_punch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ryu_punch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ryu_walkb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ryu_walkb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ryu_walkf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ryu_walkf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sonicboom() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sonicboom", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
